version: '3.8'

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:13
    container_name: "db"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  web:
    container_name: web
    build: ./docker/web
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./web:/app:cached
    tty: true
    stdin_open: true
    working_dir: /app

  statusmanager-api:
    container_name: statusmanager-api
    image: node:lts
    ports:
      - 8020:8020
      - 8021:8021
    volumes:
      - ./statusmanager-api:/app:cached
    tty: true
    working_dir: /app
    depends_on:
      - db

  # questionpost-api:
  #   container_name: questionpost-api
  #   image: node:lts
  #   ports:
  #     - 8010:8010
  #   volumes:
  #     - ./questionpost-api:/app:cached
  #   tty: true
  #   working_dir: /app
  #   depends_on:
  #     - db

  common-api:
    container_name: common-api
    image: node:lts
    ports:
      - 8000:8000
    volumes:
      - ./common-api:/app:cached
    tty: true
    working_dir: /app
    depends_on:
      - db

  microsoftteams-api:
    container_name: microsoftteams-api
    image: node:lts
    ports:
      - 9000:9000
    volumes:
      - ./microsoftteams-api:/app:cached
    tty: true
    working_dir: /app
    depends_on:
      - db
